info:
  component: turbine

server:
  port: 8989

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  
eureka:
  instance:
    hostname: localhost
    port: 8761
    statusPageUrlPath: ${server.contextPath}/health
    leaseRenewalIntervalInSeconds: 25
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
#    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    healthcheck:
      enabled: true

#appConfig is a list of the services you want to watch service1,service2,etc
#turbine:
#  appConfig: reservations
#  clusterNameExpression: new String("default") 
