server:
  port: 8080
  contextPath: /${spring.application.name}

eureka:
  instance:
    hostname: localhost
    port: 8761
    statusPageUrlPath: ${server.contextPath}/health
    leaseRenewalIntervalInSeconds: 25
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    healthcheck:
      enabled: true
      
# print exception in log stack trace
logging:
  level:
    com:
      netflix:
        hystrix: DEBUG

#hystrix:
#  stream:
#    bus: 
#      enabled: true