server:
  port: 8888
  contextPath: /${spring.application.name}

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: ${server.contextPath}/status
    leaseExpirationDurationInSeconds: 30
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true