spring:
  datasource:
    url: jdbc:oracle:thin:@host:port:sid
    username: ENC(sIsuvBSsw+isj7kc6xeC9QdTJjXSmGm5)
    password: ENC(XcBjfjDDjxeyFBoaEPhG14wEzc6Ja+Xx+hNPrJyQT88=)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    platform: oracle